pipeline{
    agent any 
    environment {
        PATH = "$PATH:/etc/maven/apache-maven-3.8.4/bin"
}
stages {
    stage('GetCode'){
        steps{
            git 'https://github.com/ravdy/DevOps.git'
        }
    }
    stage('Build'){
        steps{
            sh 'mvn clean package'
        }
    }
    stage("Sonarqube analysis") {
        steps{
            withSonarqubeEnv('sonarqube-8.9.2') {
               sh 'mvn sonar:sonar'     
               }
    }
}
    }
}
